# Generated by Django 5.0.6 on 2024-06-12 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('max_load_capacity', models.FloatField(help_text='Максимальная грузоподъемность в тоннах')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_load', models.FloatField(default=0, help_text='Текущая нагрузка в тоннах')),
                ('si_content', models.FloatField(help_text='Содержание SiO2 в процентах')),
                ('fe_content', models.FloatField(help_text='Содержание Fe в процентах')),
                ('polygon', models.TextField(help_text='WKT-представление полигона')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('current_load', models.FloatField(help_text='Текущая нагрузка в тоннах')),
                ('overloading', models.FloatField(help_text='Перегруз в процентах')),
                ('si_content', models.FloatField(help_text='Содержание SiO2 в процентах')),
                ('fe_content', models.FloatField(help_text='Содержание Fe в процентах')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mining_app.truckmodel')),
            ],
        ),
    ]
