# Generated by Django 5.0.6 on 2024-06-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='number',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
