# Generated by Django 5.0.6 on 2024-06-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining_app', '0002_warehouse_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='number',
            new_name='name',
        ),
    ]
