# Generated by Django 5.0.6 on 2024-06-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_app', '0003_rename_number_warehouse_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='overloading',
            field=models.FloatField(default=900, help_text='Объем после разгрузки в тоннах'),
            preserve_default=False,
        ),
    ]
